name: Build and Release

on:
  schedule:
    - cron: '0 6 * * *'  # 每天UTC时间6点（北京时间14点）
  push:
    tags:
      - 'v*'  # 推送v开头的标签时触发

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --clean --windowed \
          --name=StudentMainKiller_Re \
          --icon=icon.ico \
          --uac-admin \
          StudentMainKiller_Re.py

    - name: Zip the Build
      run: |
        Compress-Archive -Path ./dist/* -DestinationPath ./release.zip

  release:
    needs: build
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get release version
      id: get_version
      run: |
        echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        name: "Release ${{ steps.get_version.outputs.version }}"
        body: "Auto-generated release"
        draft: false
        prerelease: false
        files: |
          release.zip
          LICENSE
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}